### ISSUE TITLE
missing ceff48b07c6ce89c5b773147a3afa4198ae508b0

### ISSUE THREAD

**Issue by ghost** [staysail/libzerotiercore#2]
hey,

i've tried to build zerotier with this repo, but it didn't worked because it complained about a mission object ceff48b07c6ce89c5b773147a3afa4198ae508b0

by the way, is this still an ongoing process/option using zerotier with nng?
because there seems to be less effort if the repo does not work and nobody realized it :-)

Cheers, Frank ;-)

**Comment by gdamore** [comment]
Its been a while since I worked on it -- and the upstream ZeroTier has changed a bit.  I'll take a look soon.

I've been thinking of a redesign of the protocol to use kcp on top of ZeroTier -- I think it would make the whole thing a bit easier to use and let me get past the message size limitations.  Stay tuned for that.

**Comment by ghost** [comment]
thanks for the update ... 👍
